Differentiate documentation target name across targets
ROOT-Sim/core pull request #102
Opened 2023-05-09 11:14 UTC by alessandropellegrini

We are concentrating the release actions in a single monorepo that gathers together all the different projects.
For this to work, we need different unique target names across the projects. This is already (mostly) true, except for the documentation target. This commit prepends the name of the repo to the doc target, for simplicity of management in the monorepo.

2023-05-10 21:02 UTC, Piccions approved these changes

2023-05-10 21:03 UTC, Piccions requested changes
The documentation pipeline now doesn't work, because it still refers to the old ```doc``` target.

2023-06-10 05:30 UTC, alessandropellegrini commented
It has been fixed now, introducing actions version `v1.3`.

2023-06-27 21:47 UTC, Piccions approved these changes

2023-06-27 21:47 UTC, merged