Deferred fossil collection
ROOT-Sim/core pull request #86
Opened 2022-10-24 02:00 UTC by Piccions

Originally, fossil collection operations were executed synchronously after a new GVT was computed.
With this PR, fossil collection of a LP is deferred until we have to process a message for it. This measurably improves performance thanks to the improved cache friendliness.

Also, the memory footprint of the model exposed library has been halved with those changes:
- The ```Normal()``` number generation API does not cache anymore the second generated random number; instead it returns both numbers
- The pointer set by the model developer with the ```SetState()``` API is not saved anymore in the model memory allocator; that means that it can only be safely used during LP initialization

Also, some other little changes:
- Improved the handling of early remote anti messages, i.e. anti messages delivered before their positive counterpart
- Improved Doxygen documentation of the process module

2022-11-16 14:16 UTC, alessandropellegrini requested changes
Thanks a lot! Some minor rollbacks as we have discussed are needed before merging this one.

2022-11-17 21:11 UTC, Piccions commented on src/ROOT-Sim.h
> +};
Done!

2022-11-17 21:11 UTC, Piccions commented on src/gvt/gvt.c
> +static __thread simtime_t gvt_partial;
Done!

2022-11-17 21:12 UTC, Piccions commented on src/lib/random/random.c
> +double Expent(void)
Done (inserted a macro in ROOT-Sim.h)

2022-11-17 21:12 UTC, Piccions commented on src/lp/lp.c
> +void SetState(void *state)
Done, the check is enabled only in the debug mode

2022-11-17 21:12 UTC, Piccions commented on src/gvt/fossil.c
> +	gvt_current = current_gvt;
Fixed!

2022-11-18 16:49 UTC, alessandropellegrini approved these changes
I am happy with this PR, thanks a lot Andrea!
Just a little note: could you update the description in the initial message removing the reference to the Normal distribution?
I am asking this because it's automatically linked in the release notes.

Thanks!

2022-11-19 06:42 UTC, merged